language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

  - pip install coveralls

  - pip install codeclimate-test-reporter

env:
  - FLASK_VERSION=1.0.2

script:
  - pytest --cov-report term-missing --cov=app/api
  - coverage run --source=app.api -m pytest && coverage report


after_success:
  - coveralls
  - codeclimate-test-reporter
