language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

  - pip install coveralls

  - pip install codeclimate-test-reporter

env:
  - FLASK_VERSION=1.0.2

script:
  - nosetests --with-coverage --cover-package=tests tests/v1


after_success:
  - coveralls
  - codeclimate-test-reporter
